title: Zhengyu Zhao<br><font style="font-family:隶书" size="5">(赵正宇)</font>
position: Associate Professor
affiliation: Xi'an Jiaotong University
affiliation_link: http://en.xjtu.edu.cn/about.html
affiliation_logo: https://ZhengyuZhao.github.io/assets/img/xjtu.png
email: zhengyu.zhao (at) xjtu.edu.cn
keywords: zhengyu zhao, zhao zhengyu, zhengyuzhao, zhaozhengyu
google_scholar: https://scholar.google.com/citations?user=pC8KpPMAAAAJ&hl=en
github_link: https://github.com/ZhengyuZhao
linkedin: https://www.linkedin.com/in/zhengyu-zhao-61361a8a/
twitter: https://twitter.com/JeremyZhaozy
avatar: https://ZhengyuZhao.github.io/assets/img/ZhengyuZhao_03.jpg
google_analytics: UA-111540567-4

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - run_jekyll.sh
  - minimal-light.gemspec
  - CNAME
